language: node_js
dist: xenial

node_js:
  - node
  - 16
  - 12
  - 8

os:
  - linux
  - windows

stages:
  - lint
  - test
  - coverage

jobs:
  include:
    - stage: lint
      node_js: 16
      script:
        - npm run lint:prettier
        - npm run lint:js
    - stage: coverage
      node_js: 16
      script:
        - npm run test:coverage

notifications:
  email: false